services:
  player-manager:
    image: player-manager:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: player-manager
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/the_hidden_cargo
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - users

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ccastano41
      - MONGO_INITDB_ROOT_PASSWORD=EndGame2019
      - MONGO_INITDB_DATABASE=the_hidden_cargo
    volumes:
      - mongo-data:/data/db
    networks:
      - users

networks:
  users:
    name: users

volumes:
  mongo-data:
