#Construccon
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests


# Desarrollo
FROM maven:3.9.6-eclipse-temurin-21

# Directorio de trabajo
WORKDIR /app

# Copiar el archivo pom.xml para pre-descargar las dependencias
COPY pom.xml .
RUN mvn dependency:go-offline
COPY --from=build /app/target/*.jar playerManager.jar

# Copiar el código fuente
COPY src ./src

# Puerto expuesto
EXPOSE 8080

# Comando para ejecutar la aplicación en modo desarrollo
# Usando spring-boot:run para tener recarga en caliente
CMD ["mvn", "-e", "spring-boot:run"]