trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - '**'

resources:
  repositories:
    - repository: SocketService
      type: github
      name: TheHiddenCargo/SocketService
      endpoint: github-connection

extends:
  template: azure-pipelines-template.yml@socket
  parameters:
    projectName: 'usersMicroService'
    servicePort: '8081'
    environment: 'production'
    additionalSteps:
      - script: |
          echo "Running User-specific build steps"
        displayName: 'User Service'
