spring:
  application:
    name: userService
  data:
    mongodb:
      uri: mongodb+srv://ccastano41:${DBPASSWORD}@cluster0.brnvy.mongodb.net/the_hidden_cargo?retryWrites=true&w=majority&appName=Cluster0
      database: the_hiddn_cargo

socket-server:
  host: 0.0.0.0
  port: 8085
  origin: "*"
      