spring:
  application:
    name: userService
  data:
    mongodb:
      uri: mongodb+srv://ccastano41:<db_password>@cluster0.brnvy.mongodb.net/the_hidden_cargo?retryWrites=true&w=majority&appName=Cluster0
      database: the_hiddn_cargo