name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    uses: TheHiddenCargo/central-pipelines/.github/workflows/sonarcloud-analysis.yml@573efc0e1ace509f31ece2235ebecd7ec2b859a9
    with:
      java-version: '21'
      branch-name: 'main'
      coverage-exclusions: 'src/main/java/arsw/tamaltolimense/playermanager/config/**/*,src/main/java/arsw/tamaltolimense/playermanager/controller/**/*,src/main/java/arsw/tamaltolimense/playermanager/exception/**/*,src/main/java/arsw/tamaltolimense/playermanager/repository/**/*,src/main/java/arsw/tamaltolimense/playermanager/model/**/*,src/main/java/arsw/tamaltolimense/playermanager/PlayerManager.*'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}